/**
 * ICSE Class 10 Chapter Data
 * Complete syllabus mapping for all subjects
 */

export const ICSE_SUBJECTS = [
    'Physics',
    'Chemistry',
    'Biology',
    'Mathematics',
    'History & Civics',
    'Geography',
    'English Language',
    'English Literature',
    'Computer Applications',
];

export const ICSE_CHAPTERS: Record<string, string[]> = {
    Physics: [
        'Force, Work, Power & Energy',
        'Light',
        'Sound',
        'Electricity',
        'Heat',
        'Magnetism',
        'Current Electricity',
        'Household Circuits',
    ],
    Chemistry: [
        'Periodic Table',
        'Chemical Bonding',
        'Acids, Bases and Salts',
        'Metallurgy',
        'Mole Concept',
        'Electrolysis',
        'Chemical Reactions',
        'Organic Chemistry',
    ],
    Biology: [
        'Cell Biology',
        'Photosynthesis',
        'Respiration',
        'Circulatory System',
        'Nervous System',
        'Excretory System',
        'Reproductive System',
        'Genetics and Evolution',
    ],
    Mathematics: [
        'Commercial Mathematics',
        'Compound Interest',
        'Linear Inequations',
        'Quadratic Equations',
        'Ratio and Proportion',
        'Factorization',
        'Matrices',
        'Arithmetic & Geometric Progression',
        'Coordinate Geometry',
        'Trigonometry',
        'Statistics',
        'Probability',
        'Mensuration',
        'Similarity',
    ],
    'History & Civics': [
        'First War of Independence 1857',
        'Growth of Nationalism',
        'First World War',
        'Rise of Dictatorships',
        'Second World War',
        'United Nations',
        'The Union Legislature',
        'Union Executive',
        'State Government',
        'Judiciary',
    ],
    Geography: [
        'India - Location',
        'Physiographic Divisions',
        'Drainage System',
        'Climate',
        'Natural Vegetation',
        'Agriculture',
        'Mineral Resources',
        'Industries',
        'Transport and Communication',
    ],
    'English Language': [
        'Comprehension',
        'Grammar',
        'Composition',
        'Letter Writing',
        'Essay Writing',
    ],
    'English Literature': [
        'Prose',
        'Poetry',
        'Drama',
    ],
    'Computer Applications': [
        'Binary System',
        'Java Fundamentals',
        'Objects and Classes',
        'Constructors',
        'Library Classes',
        'Conditional Statements',
        'Loops',
        'Arrays',
    ],
};
